org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true

mod_id=keybind_priority
mod_name=Keybind Priority
mod_version=0.1.2
mod_authors=Comethri
mod_license=MIT
mod_group=com.comethri.keybindpriority

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.251
neo_version_range=[21.1.0,)
loader_version_range=[4,)
